---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Execute clone command
      command: echo "Cloning 123"
      register: result

    - name: Show command result
      debug:
        var: result.stdout
